# SPDX-FileCopyrightText: 2020 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

[project]
name = "snerge-bot"
version = "0.0.1"

requires-python = ">=3.13, <4"
dependencies = [
    "aiohttp~=3.13",
    "python-json-logger~=4.1",
    "yarl~=1.23",
]

[project.optional-dependencies]

dev = ["bastet~=0.2", "types-beautifulsoup4"]
download = ["beautifulsoup4~=4.14"]
reviews = ["epicstore-api"]

[tool.bastet]

disable = ["test", "pylint", "flake8", "bandit"]

[tool.black]

line-length = 100

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]

select = ["ALL", "TD"]
ignore = [
    "D200",  # Single line doc strings do not need to fit on a single line in code.
    "D202",  # Allow a blank line after docstring.
    "D203",  # Use Zero blank lines before docstring, as per D211.
    "D212",  # Multi-line docstring summary should start at the second line.

    "D10",

    "ASYNC230",  # I'm playing fast-and-loose with open() in aysnc.
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]

# Section ordering
section-order = ["future", "typing", "standard-library", "third-party", "first-party", "local-folder"]
sections = {"typing" = ["typing", "types", "typing_extensions", "collections.abc"]}
required-imports  = ["from __future__ import annotations as _future_annotations"]

[tool.isort]
profile = "black"
py_version = 313

# Section ordering
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_typing = ["typing", "types", "typing_extensions", "collections.abc"]

# Always have deferred annotation processing. We rename it so we can use 'annotations' as a name.
add_imports = ["from __future__ import annotations as _future_annotations"]

# 9 is black compatible, but does not look great
multi_line_output = 3
